# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
    - test
    - release

before_script:
  - yarn install

node:6:
  image: node:6
  stage: test
  script:
    - yarn test

node:8:
  image: node:8
  stage: test
  script:
    - yarn test

node:10:
  image: node:10
  stage: test
  script:
    - yarn test

publish:
  image: node:8
  stage: release
  script:
    - yarn global add semantic-release@15 @semantic-release/gitlab-config@2
    - semantic-release -e @semantic-release/gitlab-config
